version: '3.9'

volumes:
  postgres_volume:
services:
  api:
    build: .
    command: yarn start:dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres_service
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      PORT: 3000
      JWT_SECRET: secret
      TOKEN_EXPIRED_IN: 1d
    depends_on:
      - postgres_service
    volumes:
      - ./src:/usr/src/app/src
  postgres_service:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres_volume:/data/db
