version: '3.9'

volumes:
  mongodb_volume:
services:
  api:
    build: .
    command: yarn start:dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongodb_service
    volumes:
      - ./src:/usr/src/app/src
  mongodb_service:
    image: mongo:latest
    restart: unless-stopped
#    ports:
#      - "27017:27017"
    volumes:
      - mongodb_volume:/data/db

