version: '3.9'

volumes:
  mongodb_volume:
services:
  api:
    build: .
    command: yarn start:dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      MONGODB_CONNECTION_STRING: mongodb://mongodb_service:27017
      PORT: 3000
      JWT_SECRET: secret
      TOKEN_EXPIRED_IN: 1d
    depends_on:
      - mongodb_service
    volumes:
      - ./src:/usr/src/app/src
  mongodb_service:
    image: mongo:latest
    restart: unless-stopped
#    access to db outside the container
#    ports:
#      - "27017:27017"
    volumes:
      - mongodb_volume:/data/db

